apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: service-a
    version: v3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
        version: v3
    spec:
      containers:
        - name: service-a
          image: addozhang/http-sample
          ports:
            - containerPort: 8080
          env:
            - name: app
              value: "service-a"
            - name: version
              value: "v3"
            - name: upstream
              value: "http://service-b:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  selector:
    app: service-a
    version: v3
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  labels:
    app: service-b
    version: v3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
        version: v3
    spec:
      containers:
        - name: service-b
          image: addozhang/http-sample
          ports:
            - containerPort: 8080
          env:
            - name: app
              value: "service-b"
            - name: version
              value: "v3"
            - name: upstream
              value: "http://service-c:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  labels:
    app: service-b
spec:
  selector:
    app: service-b
    version: v3
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
  labels:
    app: service-c
    version: v3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
        version: v3
    spec:
      containers:
        - name: service-c
          image: addozhang/http-sample
          ports:
            - containerPort: 8080
          env:
            - name: app
              value: "service-c"
            - name: version
              value: "v3"
---
apiVersion: v1
kind: Service
metadata:
  name: service-c
  labels:
    app: service-c
spec:
  selector:
    app: service-c
    version: v3
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

